/* generated by tools/describe.py from descriptions/demo.yaml — do not edit */
#include "../core/contract.h"

#ifdef QEMU_TARGET
static const ic_compartment_spec ic_comp_monitor __attribute__((unused)) = { 0x80100000u, 0x2000u, 0x80200000u, 0x2000u };
static const ic_compartment_spec ic_comp_attacker __attribute__((unused)) = { 0x80102000u, 0x2000u, 0x80208000u, 0x2000u };

static const ic_module_desc ic_module_monitor __attribute__((unused)) = { IC_MODULE_MAGIC, 1u, IC_MODULE_EBPF, 0x80100000u, 0x2000u, 0x80200000u, 0x2000u, 0x0u, 0u };
static const ic_module_desc ic_module_attacker __attribute__((unused)) = { IC_MODULE_MAGIC, 1u, IC_MODULE_NATIVE, 0x80102000u, 0x2000u, 0x80208000u, 0x2000u, 0x0u, 0u };
#else
static const ic_compartment_spec ic_comp_monitor __attribute__((unused)) = { 0x8002000u, 0x2000u, 0x20004000u, 0x2000u };
static const ic_compartment_spec ic_comp_attacker __attribute__((unused)) = { 0x8004000u, 0x2000u, 0x20008000u, 0x2000u };

static const ic_module_desc ic_module_monitor __attribute__((unused)) = { IC_MODULE_MAGIC, 1u, IC_MODULE_EBPF, 0x8002000u, 0x2000u, 0x20004000u, 0x2000u, 0x0u, 0u };
static const ic_module_desc ic_module_attacker __attribute__((unused)) = { IC_MODULE_MAGIC, 1u, IC_MODULE_NATIVE, 0x8004000u, 0x2000u, 0x20008000u, 0x2000u, 0x0u, 0u };
#endif
