#!/usr/bin/env python3
"""Compile declarative compartment/module descriptions (YAML) into a C header
that implements contract.h types. This is the first validation gate: anything
wrong fails here, on the host, before any byte reaches the target.

Usage: tools/describe.py descriptions/demo.yaml descriptions/demo.h
"""
import re
import sys

try:
    import yaml
except ImportError:
    sys.exit("pyyaml required: pip install pyyaml")

CONTRACT_VERSION = 1
ALIGN = 0x1000
MIN_SIZE = 0x400
KINDS = {"ebpf": "IC_MODULE_EBPF", "native": "IC_MODULE_NATIVE"}


def fail(msg):
    sys.exit(f"describe: {msg}")


def ident(name, what):
    if not re.match(r"[A-Za-z_][A-Za-z0-9_]*$", name or ""):
        fail(f"{what} '{name}' is not a C identifier")
    return name


def uint(value, what):
    if not isinstance(value, int) or value < 0:
        fail(f"{what} must be a non-negative integer, got {value!r}")
    return value


def check_compartment(c):
    name = ident(c.get("name"), "compartment name")
    for field in ("text_base", "text_size", "sram_base", "sram_size"):
        v = uint(c.get(field), f"{name}.{field}")
        if "base" in field and v % ALIGN:
            fail(f"{name}.{field} 0x{v:X} is not 4 KiB aligned")
        if "size" in field and (v < MIN_SIZE or v & (v - 1)):
            fail(f"{name}.{field} 0x{v:X} must be a power of two >= 0x400")
    return name, c


def check_module(m, compartments):
    name = ident(m.get("name"), "module name")
    kind = m.get("kind")
    if kind not in KINDS:
        fail(f"module {name}: kind must be one of {sorted(KINDS)}")
    comp = m.get("compartment")
    if comp not in compartments:
        fail(f"module {name}: compartment '{comp}' does not exist")
    entry = uint(m.get("entry_offset", 0), f"{name}.entry_offset")
    if entry % 2:
        fail(f"module {name}: entry_offset must be 2-byte aligned")
    text_size = compartments[comp]["text_size"]
    if entry >= text_size:
        fail(f"module {name}: entry_offset {entry} is outside its text region")
    return name, m, KINDS[kind]


def main():
    if len(sys.argv) != 3:
        fail("usage: describe.py <descriptions.yaml> <output.h>")
    doc = yaml.safe_load(open(sys.argv[1])) or {}
    if uint(doc.get("contract_version"), "contract_version") != CONTRACT_VERSION:
        fail(f"contract_version must be {CONTRACT_VERSION}")

    compartments = {}
    for c in doc.get("compartments") or []:
        name, c = check_compartment(c)
        if name in compartments:
            fail(f"duplicate compartment '{name}'")
        compartments[name] = c

    modules = {}
    for m in doc.get("modules") or []:
        name, m, kind_c = check_module(m, compartments)
        if name in modules:
            fail(f"duplicate module '{name}'")
        modules[name] = (m, kind_c)

    out = [f"/* generated by tools/describe.py from {sys.argv[1]} — do not edit */",
           "#include \"contract.h\"", ""]
    for name, c in compartments.items():
        out.append(
            f"static const ic_compartment_spec ic_comp_{name} "
            f"__attribute__((unused)) = {{ "
            f"0x{c['text_base']:X}u, 0x{c['text_size']:X}u, "
            f"0x{c['sram_base']:X}u, 0x{c['sram_size']:X}u }};")
    out.append("")
    for name, (m, kind_c) in modules.items():
        comp = compartments[m["compartment"]]
        entry = uint(m.get("entry_offset", 0), "entry_offset")
        out.append(
            f"static const ic_module_desc ic_module_{name} "
            f"__attribute__((unused)) = {{ IC_MODULE_MAGIC, "
            f"{CONTRACT_VERSION}u, {kind_c}, "
            f"0x{comp['text_base']:X}u, 0x{comp['text_size']:X}u, "
            f"0x{comp['sram_base']:X}u, 0x{comp['sram_size']:X}u, "
            f"0x{entry:X}u, 0u }};")
    open(sys.argv[2], "w").write("\n".join(out) + "\n")
    print(f"describe: {len(compartments)} compartments, "
          f"{len(modules)} modules -> {sys.argv[2]}")


if __name__ == "__main__":
    main()
